labels:
  'ğŸš€Feat':
    include:
      - '\bFeat\b'
  'ğŸ¨Design':
    include:
      - '\bDesign\b'
  'âœ¨Fix':
    include:
      - '\bFix\b'
  'â™»ï¸Refactor':
    include:
      - '\bï¸Refactor\b'